### ISSUE TITLE
Trouble installing from pip

### ISSUE THREAD

**Issue by tushar-rishav** [GochoMugo/remindme#8]
I am getting an error while installing `remindme` from PyPi. IIUC `colorama` should get installed with the package itself as it's one among the dependencies? `install_requires` should handle that automatically. Anything I'm missing here?
This is the partial log.
```sh
Collecting remindme
  Downloading remindme-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-EJv9r3/remindme/setup.py", line 6, in <module>
        import remindme.metadata as metadata
      File "/tmp/pip-build-EJv9r3/remindme/remindme/__init__.py", line 2, in <module>
        from .cli import run
      File "/tmp/pip-build-EJv9r3/remindme/remindme/cli.py", line 7, in <module>
        from . import config
      File "/tmp/pip-build-EJv9r3/remindme/remindme/config.py", line 3, in <module>
        import colorama
    ImportError: No module named colorama
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-EJv9r3/remindme/

```

**Comment by GochoMugo** [comment]
I was supposed to blank out `remindme/__init__.py`, as it just marks the directory a module. Sorry for that! :wink:
